spring:
  application:
    name: yu-ai-code-mother-backend
  profiles:
    active: local
  devtools:
    add-properties: false

server:
  port: 8123
  servlet:
    context-path: /api
# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.jamin.codecube.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn

logging:
  level:
    web: debug

